# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71180afc50f119f2cec3d9a711b1b2b81ccbe0cdc7424347e585c8a4fc03c26736c3353487b340d74c78dbafa3ceba4576d7bfa8940de69adf9bea9ef0414bda
  beats_client_id: 'gn6mbnkvwgpywygfprdyp8at'
  beats_user_id: '146286780193178112'

test:
  secret_key_base: 09ae7fe39275fb6a017c632b1ed16d3166836cf6c6387e1afd038cecb0cb0d8ef28108b9c1ced9415a453d9311b76d3ae6d61345cf2ae0811e7745d9feebf1f4
  beats_client_id: 'gn6mbnkvwgpywygfprdyp8at'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  beats_client_id: 'gn6mbnkvwgpywygfprdyp8at'
  beats_user_id: '146286780193178112'
